services:
  plex-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plex-mcp
    labels:
      - com.centurylinklabs.watchtower.enable=false
    ports:
      - "${PLEX_MCP_PORT:-9150}:${PLEX_MCP_PORT:-9150}"
    env_file:
      - .env
    volumes:
      - /mnt/cache/appdata/plex-mcp/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9150/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - jakenet

networks:
  jakenet:
    external: true 